-------------------------------------------------------------------------------
Test set: org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest
-------------------------------------------------------------------------------
Tests run: 245, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 15.42 s <<< FAILURE! -- in org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest
org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test056 -- Time elapsed: 0.044 s <<< FAILURE!
java.lang.AssertionError: Expecting exception: RuntimeException
	at org.junit.Assert.fail(Assert.java:89)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test056(ClassicConfiguration_ESTest.java:731)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

