-------------------------------------------------------------------------------
Test set: org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest
-------------------------------------------------------------------------------
Tests run: 280, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 24.71 s <<< FAILURE! -- in org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest
org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test051 -- Time elapsed: 0.052 s <<< ERROR!
org.flywaydb.core.api.FlywayException: Unable to resolve location classpath:report.
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.findResourceNamesAndParentURLs(ClassPathScanner.java:220)
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.<init>(ClassPathScanner.java:75)
	at org.flywaydb.core.internal.scanner.ClasspathClassScanner.scanForType(ClasspathClassScanner.java:37)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.loadCallbackLocation(ClassicConfiguration.java:1198)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test051(ClassicConfiguration_ESTest.java:597)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test046 -- Time elapsed: 0.080 s <<< ERROR!
org.flywaydb.core.api.FlywayException: Unable to resolve location classpath:null.
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.findResourceNamesAndParentURLs(ClassPathScanner.java:220)
	at org.flywaydb.core.internal.scanner.classpath.ClassPathScanner.<init>(ClassPathScanner.java:75)
	at org.flywaydb.core.internal.scanner.ClasspathClassScanner.scanForType(ClasspathClassScanner.java:37)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.loadCallbackLocation(ClassicConfiguration.java:1198)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.loadCallbackPath(ClassicConfiguration.java:1184)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setCallbacksAsClassNames(ClassicConfiguration.java:1156)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test046(ClassicConfiguration_ESTest.java:524)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test048 -- Time elapsed: 0.111 s <<< FAILURE!
java.lang.AssertionError: Exception was not thrown in org.flywaydb.core.internal.logging.buffered.BufferedLog but in org.flywaydb.core.internal.logging.EvolvingLog.debug(EvolvingLog.java:52): java.lang.NullPointerException
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:111)
	at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:48)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test048(ClassicConfiguration_ESTest.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)

