JUnit version 4.13.2
...........................................................................................................................................................................................................................E......E.....................................E............................
Time: 13.035
There were 3 failures:
1) test082(org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest)
java.lang.AssertionError: Exception was not thrown in org.flywaydb.core.internal.logging.buffered.BufferedLog but in org.flywaydb.core.internal.logging.EvolvingLog.debug(EvolvingLog.java:52): java.lang.NullPointerException
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:111)
	at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:48)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test082(ClassicConfiguration_ESTest.java:899)
2) test079(org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest)
java.lang.AssertionError: Expecting exception: RuntimeException
	at org.junit.Assert.fail(Assert.java:89)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test079(ClassicConfiguration_ESTest.java:848)
3) test077(org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest)
java.lang.AssertionError: Exception was not thrown in org.flywaydb.core.internal.logging.buffered.BufferedLog but in org.flywaydb.core.internal.logging.EvolvingLog.debug(EvolvingLog.java:52): java.lang.NullPointerException
	at org.evosuite.runtime.EvoAssertions.assertThrownBy(EvoAssertions.java:111)
	at org.evosuite.runtime.EvoAssertions.verifyException(EvoAssertions.java:48)
	at org.flywaydb.core.api.configuration.ClassicConfiguration_ESTest.test077(ClassicConfiguration_ESTest.java:823)

FAILURES!!!
Tests run: 290,  Failures: 3

